replicaCount: 1

image:
  repository: ghcr.io/ed-ad/git-instaweb
  tag: "latest"
  pullPolicy: IfNotPresent
  build:
    enabled: true
    context: ../../docker/git-instaweb
    dockerfile: Dockerfile

service:
  type: ClusterIP
  port: 8080

repo:
  mountPath: /srv/git
  repoPath: repo.git
  hostPath:
    enabled: true
    path: /var/lib/stupid-git/repos
    type: DirectoryOrCreate

resources: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
