apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git-instaweb.fullname" . }}-config
  labels:
    {{- include "git-instaweb.labels" . | nindent 4 }}
data:
  lighttpd.conf: |
    server.modules = ("mod_access", "mod_accesslog", "mod_alias", "mod_cgi", "mod_setenv")
    server.document-root = "/var/www"
    server.port = {{ .Values.service.port }}
    server.bind = "0.0.0.0"
    server.pid-file = "/var/run/lighttpd.pid"
    server.username = "www-data"
    server.groupname = "www-data"
    server.errorlog = "/var/log/lighttpd/error.log"
    accesslog.filename = "/var/log/lighttpd/access.log"
    accesslog.format = "%h %V %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""

    setenv.set-environment = (
      "GIT_PROJECT_ROOT" => "{{ .Values.repo.mountPath }}",
      "GIT_HTTP_EXPORT_ALL" => ""
    )

    alias.url = ( "" => "/usr/local/bin/git-http-backend-wrapper" )
    cgi.assign = ( "" => "" )
